/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PCD_P5;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author jujis
 */
public class GeneradorFrame extends javax.swing.JFrame {

    /**
     * Creates new form GeneradorFrame
     */
    public GeneradorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GeneradorFrame GF = new GeneradorFrame();
        GF.setSize(800, 400);
        GF.setBackground(Color.lightGray);
        GF.setLocation(100, 100);

        CanvasCentro canvas = new CanvasCentro(800, 400);
        GF.add(canvas);
        GF.setVisible(true);
        Centro centro = new Centro(canvas);

        Random rn = new Random();

        for (int i = 1; i <= 10; i++) {
            Runnable cliente;
            if (Math.random() <= 0.4) {
                cliente = new Rehabilita(centro);
            } else {
                cliente = new Masaje(centro);
            }

            Thread hiloCliente = new Thread(cliente);
            hiloCliente.start();

            try {

                Thread.sleep(rn.nextInt(1, 2) * 1000); // Intervalo de 1 a 2 segundos
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

