/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica3_pcd;

import java.awt.*;

/**
 *
 * @author jujis
 */
public class PilaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        PilaFrame PF = new PilaFrame();
        PF.setSize(600, 200);
        PF.setBackground(Color.lightGray);
        PF.setLocation(100, 100);

        CanvasPila CP = new CanvasPila(600, 200);
        PF.add(CP);
        PF.setVisible(true);
        PilaLenta mipila = new PilaLenta(20, CP);

        Consumidor C1 = new Consumidor(mipila);

        Productor h1 = new Productor(mipila);
        Productor h2 = new Productor(mipila);

        Thread h3 = new Thread(C1);
        Thread h4 = new Thread(C1);

        try {
            h1.start();
            h2.start();
            h3.start();
            h4.start();
            h1.join();
            h2.join();
            h3.join();
            h4.join();
        } catch (InterruptedException e) {
            System.out.println("Probelmas con los hilos");
        }

        mipila.GetNum();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
